default_data_source:
  driver: 'Proton ODBC Driver (Unicode)'
  url: 'http://localhost:8123'
  database: 'default'
  uid: 'default'
  pwd: ''
invalid_data_source:
  driver: 'Proton ODBC Driver (Unicode)'
  url: 'http://localhost:8123'
  database: 'system'
  uid: 'system'
  pwd: 'pasword'
